### ISSUE TITLE
Uurimuslike tegevuste otsinguvorm

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#10]
Platvormi kasutajad saavad kasutada uuringuteemade otsinguks kasutada otsinguvormi.

![screen shot 2015-02-06 at 13 24 25](https://cloud.githubusercontent.com/assets/380007/6078632/8d9d3c38-ae03-11e4-940c-8e2e724786e5.png)

**Comment by mbrikker** [comment]
Pealkiri peaks olema "Uurimuslike tegevuste otsinguvorm".
