### ISSUE TITLE
Grupi logo -> Uuringulaeka logo

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#102]
![screen shot 2016-04-15 at 15 35 13](https://cloud.githubusercontent.com/assets/380007/14561554/b8f7b8a0-031f-11e6-8e4f-5454a18ea0a8.png)

**Comment by mbrikker** [comment]
Erinevad logoversioonid on saadaval siin: https://drive.google.com/folderview?id=0B1cCT4KQ-CA8SHoySEJhbWp3M0k&usp=sharing
Soovituslik on kasutada mõnda ilma kirjata versiooni, nt. "Ark_logoRGB_small color.jpg" kaustas JPGLogoRGB
