### ISSUE TITLE
Uurimuslike tegevuste märksõnade põhine otsing

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#11]
Kasutajal on võimalik otsida / sirvida uurimisteemasid märksõna pilve abil.

![screen shot 2015-02-06 at 13 35 23](https://cloud.githubusercontent.com/assets/380007/6078772/51a9d8c4-ae05-11e4-9be7-8d6841d0e7b8.png)

**Comment by mbrikker** [comment]
"Uurimisteemade märksõnade põhine otsing" peaks olema hoopis "uurimuslike tegevuste märksõnade põhine otsing".
