### ISSUE TITLE
Kuidas on seotud õpilase ja õpetaja töövood?

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#13]
- mis hetkel puutuvad kokku kaks rolli süsteemis?
- kuidas (mis tasandil) toimub nende omavaheline suhtlus?

**Comment by urmash** [comment]
- A.Kui õpetaja kutsub õpilase portaali ja õpilane kasutab linki
   liitumiseks
   B.Kui õpilane määratleb õpetaja, kes kasutab juba portaali või lisab
   õpetaja kontakti, millele õpetaja vastab portaalis registreerumisega


   - Enamus suhtlust toimub väljaspool portaali vahenditega vahetult
   klassis, e-mail, gtalk, im, skype, fb, jne
   - Ülesanded (activitid), mida õpetaja õpilastele jagab ilmuvad õpilasele
   ja õpilane kogub oma tööd portaali välisesse e-portfooliosse



<= Paremini, ikka paremini, UrmasH:)


6. veebruar 2015 15:04 kirjutas Priit Tammets <notifications@github.com>:
