### ISSUE TITLE
Esmakordne sisenemine - õpilane

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#18]
Juhul, kui kasutaja märgib end learner-staatuseks registreerimisel ( #7 ), kuvada talle esmaskordsel sisenemisel järgnevat vormi:

![screen shot 2015-04-01 at 10 25 53](https://cloud.githubusercontent.com/assets/380007/6936341/8bb39b58-d859-11e4-9787-c7c4a6fc68c5.png)

**Comment by mbrikker** [comment]
"What I would like to do and learn in the Arc of Inquiry" peaks olema "What would I like to do and learn in the Ark of Inquiry".
