### ISSUE TITLE
Teema lisamise vorm - asukoha lisamine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#19]
Lisada teema lisamise vormile ( #8  ) märkeruut Kohapealne tegevus (jah/ei) ning juhul kui valitud, siis tekstikast "Aadress".

![img_3079](https://cloud.githubusercontent.com/assets/380007/6686978/2049604c-ccaf-11e4-8277-35d102d0a9a4.JPG)

**Comment by sanderaido** [comment]
Kas need "Web-based" ja "Physical location" on radio button'id või checkbox'id? St. kas mõlemaid saab korraga ka valida?

**Comment by tammets** [comment]
Checkbox. Lisaks web-based alla tekstkast.

**Comment by sanderaido** [comment]
af65f50c17a97b189fc42da19056a71f5514288b
