### ISSUE TITLE
Uurimislike tegevuste repositoorium

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#2]
Repository of inquiry activities should allow to upload links to inquiry activities (not stored in the platform) and add meta-data to these. Meta-data elements (textual information) are specified in the WP2 of the Ark of Inquiry project and negotiated during development of the platform. The repository should allow to search activities based on the meta-data. Which of the elements are available for search is negotiated during development of the platform. In case of registered learners there is an additional feature of the repository: it generates a list of recommended activities based on matching the characteristics of learners and inquiry activities. Learners’ characteristics include registration information and information generated through evaluation service. In case of registered learners there should be possible to indicate by the learner if s/he has started/completed a particular activity (check-boxes + text field for comments/reflection/link to external report). 

A teacher should have the possibility to extract this information about his/her learners and the administrators should get it about all learners. All together there is expected at least 100 inquiry activities.

**Comment by mbrikker** [comment]
"Uurimistööde repositoorium" peaks olema hoopis "Uurimuslike tegevuste repositoorium".
