### ISSUE TITLE
Uurimusliku õppe pass

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#20]
Passport on avalik profiilivaade, milles kuvatakse õpilase saavutused ning ülevaade tema ja temaga seotud tegevustest. Passport kuvab kasutaja profiilipildi, ees-ja perenime, omandatud õpimärgid ja auhinnad ning tegevused koos profiilipildi ja kuupäevaga.

![screen shot 2015-03-17 at 15 44 56](https://cloud.githubusercontent.com/assets/380007/6688537/e620bef2-ccbc-11e4-8e7c-459b114e878c.png)

**Comment by mbrikker** [comment]
"Õpilase passport" peaks olema "Uurimusliku õppe pass".
