### ISSUE TITLE
Proficiency level & Covered phases

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#24]
Tegevuse registreerimisvormis on järgmised valikud:
- Proficiency level
- Covered phases
- Phases Departing From the Proficiency Level

Küsimus - Mis rolli mängib nendest viimane valik "Phases Departing From the Proficiency Level"?
Küsimus 2 - Kas tegevusel võib olla ka mitu Proficiency level-it?

**Comment by mbrikker** [comment]
"Teema registreerimisvormi" asemel peaks olema "tegevuse registreerimisvorm"
1) mõeldud on seda hetke, kui üks või enam viiest uurimusliku õppe faasist on teistest erineva raskusastmega (proficiency level), siis tuuakse need välja.
2) Tegevusel (mitte teemal) saab olla ainult üks proficiency level, kuid võib esineda erineva tasemega faase tegevuse raames (vt. 1)
