### ISSUE TITLE
Uue teema lisamine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#28]
HTK serveris ei õnnestu lisada uut teemat. Täites ära teema lisamise vormi, kuvatakse teadet edukast lisamisest kuid nimekirjas seda ei kuvata.

**Comment by sanderaido** [comment]
Hetkel sain teema isegi loodud, kuid vahepeal tõesti tõrgub. Ei saa hetkel kodust sinna HTK serverisse sisse, tulen hommikul varem kohale ja vaatan üle, aiman isegi mis viga võib olla.

**Comment by sanderaido** [comment]
Viga oli kasutajaõigustes, kahtlane käitumine WP poolt. Kuigi kasutajarollil on olemas õigus `read_inq_activity`, on see Pods'i plugina poolt loodud ning millegipärast teema lisamisel paistab, nagu kasutajal ei oleks õigust isegi teemat näha (kuigi õigus on tegelikult olemas, ei suudagi põhjust leida sellele anomaaliale). Lisasin kasutajarollidele käsitsi uue õiguse `read_inq`, mis annab ka päringutes õige tulemuse ja töötab nagu peab. Edaspidi mitte kasutada õigust `read_inq_activity`.
