### ISSUE TITLE
Pädevuste hindamismoodul

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#3]
Evaluation service should allow to both registered and non-registered users to fill in diagnostic tests and questionnaires to assess their inquiry experiences, skills and RRI awareness and to build a portfolio in which reports on formative assessment dialogues, reflections, products, peer feedback, and skills tests could be collected to form the base of formative assessment (textual information + links to external materials). 

Technically there should be possible to present a number of tests (assessing different aspects and appropriate to different age groups) that will be automatically scored (multiple choice answers to questions where different type of media - text, photo, image, video, audio - can be used) or sent to human-based inspection to a teacher associated with the learner or to the system (if a teacher is not specified then the answers will be stored in the system but not fed back to the learner - information can be used for research purposes). If a user is registered then s/he should be able to link the outcomes to his/her user account. In case of learners this information is then used as a characteristic to make a list of recommended activities. 

The portfolio of a learner should be accessible for the teacher associated with him/her, the teacher should be able to upload comments to learner’s portfolio.

**Comment by mbrikker** [comment]
Piletitekst: Evaluation service should allow to both registered and non-registered users to fill in diagnostic tests and questionnaires to assess their inquiry experiences, skills and RRI awareness and to build a portfolio in which reports on formative assessment dialogues, reflections, products, peer feedback, and skills tests could be collected to form the base of formative assessment (textual information + links to external materials). Technically there should be possible to present a number of tests (assessing different aspects and appropriate to different age groups) that will be automatically scored (multiple choice answers to questions where different type of media - text, photo, image, video, audio - can be used) or sent to human-based inspection to a teacher associated with the learner or to the system (if a teacher is not specified then the answers will be stored in the system but not fed back to the learner - information can be used for research purposes).
Kommentaar: Vormid kattavad mingi osa sellest, testide osa hetkel puudu (+/-)

Piletitekst: If a user is registered then s/he should be able to link the outcomes to his/her user account. In case of learners this information is then used as a characteristic to make a list of recommended activities.
Kommentaar: tegevuste tulemeid saab profiililt vaadata. Soovitusi sellel alusel teha ei saa. (+/-)

Piletitekst: The portfolio of a learner should be accessible for the teacher associated with him/her, the teacher should be able to upload comments to learner’s portfolio.
Kommentaar: Portfolio=profile page, on õpetajale kättesaadav. Kas saaks kasutada sama kommenteerimisvõimalust ka profiili puhul nagu see on grupivaates? (+/-)
