### ISSUE TITLE
Uurimuslike faaside ja tulemuste tüüpide arv

### ISSUE THREAD

**Issue by sanderaido** [centre-for-educational-technology/Uuringulaegas#30]
Hetkel on dokumentatsioonis kirjeldatud 5 uurimuslikku faasi ja 4 evidence'i tüüpi:
>COVERED INQUIRY PHASES: (orientation, conceptualisation, investigation, conclusion, discussion)
EVIDENCE ON THE SUCCESS OF THE ACTIVITY: (Direct empirical evidence, Indirect empirical evidence, Theoretical evidence, and/or Ecological evidence)

Kas need faasid ja evidence'i tüübid võivad kunagi muutuda/lisanduda või on need ette määratud ja tulevikus ei muutu (juba süsteemi töötamise ajal)? Ei mõtle tõlget teistesse keeltesse, vaid üldiselt nende arvu ja tähendust.

**Comment by MarianneLind** [comment]
Uurimusliku õppe faasid ei muutu, need on ette määratud. Evidence´i tüübid ei tohiks ka muutuda (peab täpsustama)
