### ISSUE TITLE
Teema loomisel multiselect väljad ei välista juba lisatud väärtusi

### ISSUE THREAD

**Issue by sanderaido** [centre-for-educational-technology/Uuringulaegas#31]
Näiteks Domeene ja Faase saab lisada samu mitu tükki.

**Comment by mbrikker** [comment]
Kas, kuidas ja mis hetkel on võimalik domeene valikusse lisada? Reaalsete tegevuste sisestamisel jäi olemasolevatest väheks, hilisemalt hakkab sama mure ilmselt korduma, et ei osata tegevust ühegi valikus oleva domeeni alla lahterdada ja siis võiks kuidagimoodi saada neid lisada.

**Comment by tammets** [comment]
Süsteemi poolt oleks lihtsam andmeid kasutada kui domeenid oleksid siiski võimalikult täpselt enne sisestatud, mitte lasta kasutajal neid vabas vormis lisada. Kas oleks võimalik teil edastada meile täpsustatud nimekiri domeene ning vajadusel saab admin neid juurde lisada?

**Comment by mbrikker** [comment]
Järgnevad 26 domeeni peaks katma kõik juba olemasolevad ja võimalikud hiljem lisanduvad tegevused: astronomy, biology, chemistry, ecology, evolution, geology, paleontology, physics, geometry, logic, probability, statistics, computer science, materials science, engineering, technology, mathematics, anatomy, arts, grammar, social sciences, botany, geophysics, algebra, calculus, trigonometry.

**Comment by sanderaido** [comment]
Algses domeenide nimekirjas oli ka electricity, kas see jääb alles või võeti see domeen ära?

**Comment by mbrikker** [comment]
"Electricity" peaks olema pelgalt topic, mis kuulub domeeni "Physics" alla ehk siis ühesõnaga, pole vaja elektrile oma domeeni.
