### ISSUE TITLE
Kasutajaks registreerimine - City of Residence*

### ISSUE THREAD

**Issue by mbrikker** [centre-for-educational-technology/Uuringulaegas#36]
Kasutaja registreerimisel küsitakse linna "City of Residence" aga mitte riiki. Kas oleks võimalik enne linna lisada ka riigi küsimine ankeedile?

**Comment by tammets** [comment]
Täpsustuseks - mis oleks riigi küsimise eesmärk?

**Comment by mbrikker** [comment]
Tähelepanu juhiti sellele, et võib juhtuda, et sama linn on mitmes riigis.

**Comment by tammets** [comment]
Uus pilet tehtud (#37).
