### ISSUE TITLE
Suhtlemismoodul

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#4]
Communication service for unregistered users is only for getting messages from administrators sent to all users of the Ark of Inquiry platform. For registered users there is a possibility to get messages related to their country/language preferences or from their teacher (if they are associated with a teacher) or other users (based on user name). Teachers can send messages to the learners associated with them (option in sending messages) or to a specific user. Learners can send messages to users based on their usernames. For administrators the communication service should give a possibility to select if an announcement is sent to all users, to teachers (to all teachers/to teachers from one country/according to language preferences), to users from one country, to users according to language preferences or to a specific user (in this case there should be possible to send the same message to a big number of users based on their usernames).

**Comment by mbrikker** [comment]
Piletitekst: Communication service for unregistered users is only for getting messages from administrators sent to all users of the Ark of Inquiry platform.
Kommentaar: Kas administraator saab lõpuks saata kõigile kasutajatele korraga kirja e-mailile? (-/+)

Piletitekst: For registered users there is a possibility to get messages related to their country/language preferences or from their teacher (if they are associated with a teacher) or other users (based on user name). 
Kommentaar: Õpetaja saab postitada teateid gruppi, seega see klausel on kenasti kaetud (+)

Piletitekst: Teachers can send messages to the learners associated with them (option in sending messages) or to a specific user. Learners can send messages to users based on their usernames.
Kommentaar: See on ka enamasti kaetud grupisisese kommentaarivõimalusega. Kas väljaspool kommenteerimist on ka võimalus saata kasutajale lihtsalt e-maili? (-/+)

Piletitekst: For administrators the communication service should give a possibility to select if an announcement is sent to all users, to teachers (to all teachers/to teachers from one country/according to language preferences), to users from one country, to users according to language preferences or to a specific user (in this case there should be possible to send the same message to a big number of users based on their usernames).
Kommentaar: Sarnane esimesele punktile, kuid täiendavalt küsiks, et kui admin saab saate meile kasutajatele, kas ta saab seda teha ka kasutajagruppide kaupa? (-/+)
