### ISSUE TITLE
RRI checkbox tegevuse registreerimise vormile

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#41]
Tegevuse sisestamise vorm (#8) - lisada RRI checkbox (peale Evidence Description-it):

![screen shot 2015-07-02 at 12 16 36](https://cloud.githubusercontent.com/assets/380007/8591191/459979e8-262f-11e5-9462-8e4907b10bf3.png)

**Comment by mbrikker** [comment]
Otsinguvorm peaks võimaldama leida tegevusi vastava tugeva RRI komponendi märke järgi.

**Comment by tammets** [comment]
Lisatud piletile #48 RRI komponendi märge.
