### ISSUE TITLE
Õpimärkide omandamine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#43]
Uuringulaegas omistab õpilase staatuses olevatele kasutajatele teatud tegevuste lõpetamise eest õpimärke:

**General badges**

Welcome badge

**Peer-review**
1 PR = märk
5 PRs = märk
10 PRs = märk
50 PRs = märk

**Tegevuse lõpetamine (+ kinnitus õpetaja poolt)**
1 lõpetatud tegevus = märk
5 lõpetatud tegevust = märk
10 lõpetatud tegevust = märk
25 lõpetatud tegevust = märk
50 lõpetatud tegevust = märk
100 lõpetatud tegevust = märk

**Domain expert**
1 märk = 3 sama domeeniga tegevust lõpetatud

Lisaks on õpetajal võimalik omistada õpimärki tegevuse lõpetamisel **füüsiliste auhindadega paralleelselt**:
pronksmedal =  märk
hõbemedal = märk
kuldmedal = märk
1 märk = tunnistus, sertifikaat, diplom+ õpetaja poolne kirjeldus saadud auhinna eest
1 märk = medal või karikas + õpetaja poolne kirjeldus saadud auhinna eest
badge = Inquiry star; name of the badge: Renown Scientist

**Comment by mbrikker** [comment]
Õpimärkide pildifailid ja kirjeldused (kokku 26 õpimärki, lisatud sai lähtuvalt D1.3-st kolm märki kategooriasse "füüsiliste auhindadega paralleelselt" ja 1 märk kategooriasse "Tegevuse lõpetamine + kinnitus õpetaja poolt"):
https://drive.google.com/folderview?id=0B1cCT4KQ-CA8fk1UTkdrMlJrX1FwaV9ub2tFOHJCSlFyTlRKU3g4NGxzRlNPdUtrZmFuSG8&usp=sharing

**Comment by tammets** [comment]
+ "welcome badge"

**Comment by mbrikker** [comment]
"Welcome badge" lisatud google drive´i.

**Comment by tammets** [comment]
Millised jäävad "Welcome badge"-i omistamise tingimused? Täidetud profiiliväljad?

**Comment by mbrikker** [comment]
Kõik kohustuslikud profiiliväljad täidetud.
