### ISSUE TITLE
Tegevuse lisamise vorm - tasememaatriks

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#46]
Väli "Proficiency level" asendada "Overall proficiency level" ning lisada ekraanipildil kuvatav tasememaatriks:

![screen shot 2015-07-10 at 12 56 54](https://cloud.githubusercontent.com/assets/380007/8616344/31ced21c-2703-11e5-94e7-2dea2693d1cf.png)

**Comment by mbrikker** [comment]
Tegevuse üldine tase peaks ka siin nähtav olema, eelnevalt tasememaatriksile. Näiteks nii:

Overall proficiency level (pick one: A B C, mandatory)
Proficiency level for inquiry phases (valida saab ainult ühe kolmest variandist iga faasi kohta, optional)
Orientation X O O 
Conceptualisation X O O
Investigation O X O
etc...

**Comment by tammets** [comment]
Ekraanipilt täiendatatud vastavalt kommentaarile.
