### ISSUE TITLE
Otsinguvorm

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#48]
Kasutajal on võimalik otsinguvormi kaudu leida tegevusi, kasutades vormis kuvatavaid väljasid ja filtreid:

![screen shot 2015-08-25 at 15 28 40](https://cloud.githubusercontent.com/assets/380007/9466511/03bce792-4b3e-11e5-843e-b931a93dc60c.png)

**Comment by tammets** [comment]
Lisatud tugeva RRI komponendi märge.

**Comment by tammets** [comment]
Learning time väärtused on esitatud akadeemiliste tundidena numbrilise väärtusena, mitte slaider.

**Comment by sanderaido** [comment]
Töötab hetkel piiratud režiimis. Otsida saab fraasi, domeeni ja/või üldise taseme järgi (proficiency level)
