### ISSUE TITLE
Auhindade moodul

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#5]
Awarding service is an inquiry passport associated with evaluation service. It is available only for registered users. For learners it has two fields: i) an overview of learner’s inquiry skills, inquiry experiences and RRI awareness (based on the evaluation service) and ii) a list of inquiry awards (the awards are presented as small images - badges). There are two types of awards - the ones given by the teachers/learners and the others given by the administrators. The teachers and learners have the possibility to issue awards to the learners based on their username. The administrator’s awards will be issued to big number of users based on their usernames (there should be possible to copy and paste the list from Excel).

**Comment by mbrikker** [comment]
Piletitekst: Awarding service is an inquiry passport associated with evaluation service. It is available only for registered users. 
Kommentaar: "Inquiry passpordina" funktsioneerib nüüd kasutaja profiilileht. Profiilileht saabki eksisteerida ainult kasutajaks registreerunutel. (+)

Piletitekst: For learners it has two fields: i) an overview of learner’s inquiry skills, inquiry experiences and RRI awareness (based on the evaluation service) and ii) a list of inquiry awards (the awards are presented as small images - badges).
Kommentaar: i)"inquiry skills" klausel saab täidetud siis kui TIPS testi tulemused saab kuidagi moodi profiililehel kuvada, "inquiry experiences" klausli jaoks peaksime ilmselt tegema kolma lisabadge'i, mida õpetaja saaks anda ning mis kujutaks endast lihtsalt "A","B" ja "C" taseme omistamist, "RRI awarenessi" koha pealt pean täpsustama ii) auhinnad (badges) kuvatakse profiililehel. (-/+)

Piletitekst: There are two types of awards - the ones given by the teachers/learners and the others given by the administrators. The teachers and learners have the possibility to issue awards to the learners based on their username. The administrator’s awards will be issued to big number of users based on their usernames (there should be possible to copy and paste the list from Excel).
Kommentaar: Adminisraatoripoolsed auhinnad osaliselt automatiseeritud, manuaalselt tuleb anda ainult neid auhindu, millel on pärismaailmas vaste (diplom, medal etc...), auhindu saab anda individuaalsele kasutajale. Korraga mitmele kasutajale auhinda anda hetkel ei saa, muidu vastab adminauhindade hetkeseis kirjeldusele. (+)
Õpetajapoolne ja kaasõpilase poolne auhinna andmine pole hetkel sees. Õpetaja võiks saada teoorias oma õpilastele anda "A","B" ja "C" taseme badge´i. Kaasõpilane võiks võimalusel saada anda mingit üldist kiidumärki-badge´i (-/+)
