### ISSUE TITLE
Pagination tugi tegevuste nimekirja vaadetes

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#57]
![screen shot 2015-10-05 at 12 59 29](https://cloud.githubusercontent.com/assets/380007/10277769/f21ed688-6b60-11e5-95f8-7a9e07097ec5.png)

**Comment by sanderaido** [comment]
Mille järgi tegevusi järjestama peaks? Loomise kuupäeva? Pealkirja tähestiku järgi?

**Comment by mbrikker** [comment]
Viimasena lisatud tegevus esimesena.
