### ISSUE TITLE
Haldusliides

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#6]
Administration service is for users that are assigned by the developers of the platform. In each country there will be at least one administrator. Administrator has rights and possibilities to 
- send general messages through community service 
- add and adapt tests/questionnaires in evaluation service
- make changes in user management service (to change personal data of users)
- upload inquiry activities and related meta-data and to change it later
- collect data from evaluation service and issue awards to users based on this (there should be possible to easily download a table of data (including user name) that can be analysed in Excel or other similar programs) 
- give awards to a group of learners and to upload this information to the portal - linked to awarding service ( #5 ).

**Comment by mbrikker** [comment]
Piletitekst: Administration service is for users that are assigned by the developers of the platform. In each country there will be at least one administrator. Administrator has rights and possibilities to send general messages through community service 
Kommentaar: selline võimalus olemas (+)

Piletitekst: add and adapt tests/questionnaires in evaluation service
Kommentaar: Kui keeruline selle implementeerimine oleks, nt. selle näol, et oleks võimalus teha valikvastustega teste? (-)

Piletitekst: make changes in user management service (to change personal data of users)
Kommentaar: Funktsionaalsus olemas ja toimib kenast. (+)

Piletitekst: upload inquiry activities and related meta-data and to change it later
Kommentaar: olemas ja töötab kenasti. (+)

Piletitekst: collect data from evaluation service and issue awards to users based on this (there should be possible to easily download a table of data (including user name) that can be analysed in Excel or other similar programs)
Kommentaar: Süsteem jagab badge ja võimaldab adminil auhindu ka manuaalselt jagada. Logifailid koguvad infot, kuid kas see info on mingis vormis ka allalaetav? (-/+)

Piletitekst: give awards to a group of learners and to upload this information to the portal - linked to awarding service ( #5 ).
Kommentaar: Korraga paljudele õpilastele auhindu jagada ei saa ja "Hall of Fame" stiilis lehte hetkel pole (-)
