### ISSUE TITLE
CSV-faili loomine omistatud õpimärkide statistika kohta

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#67]
Haldusliidesest on võimalik administraatori-õigustega kasutajal alla laadida CSV-fail õpilaste nimedega, grupi kuuluvusega ning omistatud õpimärkide id-ga.

1-nimi-perenimi-grupinimi-badgeID

**Comment by pjotrsavitski** [comment]
This one needs to be a bit more explanation.

If we are talking about all the users the tare students and showing their badges. Then it could be potentially a very time-consuming task that might potentially end-up being non-functional (the time needed to extract all the data and create the file could exceed the meaningful execution time allowed by the Server; there are also other types of limitations).

Do badges get awarded based on group activities, meaning that every awarded badge has been achieved by the learning as being part of some group?

**Comment by tammets** [comment]
Do badges get awarded based on group activities, meaning that every awarded badge has been achieved by the learning as being part of some group? -** In terms of user workflow, yes. Technically I can't  confirm that.**

**Comment by mbrikker** [comment]
Users can get badges by completing other activities/actions (such as completing peer reviews etc.) than the ones recommended within a group, so I'd say badges are not based only on group activities.

**Comment by pjotrsavitski** [comment]
In that case, the requested format is not suitable and it would not be possible to extract that kind of data for all the achievements/badges. This is a logical error, of sort.

**Comment by mbrikker** [comment]
The groups and badges shouldn't be connected in that sense. It would be useful to have a way to export data about which groups a pupil is in and what badges he or she has earned. Would it be possible as two different outputs?
Like this:
1-nimi-perenimi-grupinimed
2-nimi-perenimi-badgeID

**Comment by pjotrsavitski** [comment]
Would only be able to say for sure once we get there (to the data structures), although this seems more like a task for two different files.

In general CSV are created to have the same structure for each row to make these easily usable.

Thus, probably it is possible, though will need to check the details before giving promises.

**Comment by tammets** [comment]
Additionally add e-mail and user ID to output

**Comment by pjotrsavitski** [comment]
Groups logic implemented, file structure is as follows:
USER ID
USER EMAIL
USER NAME
USER GROUPS IDENTIFIERS (comma separated)
USERS GROUPS NAMES (comma separated)

Currently all of these are columns (each row) are standalone. The file is standard CSV. There are issues that group names could have commas in them, in that case separating those would be problematic.

This could be solved in a way that each group name is a separate column.

Please do mention if any of the information is not needed (ID's).

Similar logic will be applied to the second CSV file.
