### ISSUE TITLE
Haldaja poolt teate jätmine kõigile kasutajatele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#68]
Haldajal on võimalik jätta keskkonda teade kõigile kasutajatele:

![screen shot 2015-11-10 at 9 45 36](https://cloud.githubusercontent.com/assets/380007/11057026/49f85f82-8790-11e5-93b7-fe99eaa1c1dd.jpg)

**Comment by sanderaido** [comment]
Teadet saab muuta Pages alamenüüst, Announcement'i lehel. Teate peitmiseks muuta visibility Private või status Draft (mitte kustutada tervet postitust)
