### ISSUE TITLE
Tegevuse taustapilt

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#74]
Tegevusele on võimalik tegevuse lisajal lisada taustapilti (870px x 400px), mida kuvatakse tegevuse vaate päises ja külgmise menüü taustal:

![screen shot 2016-01-25 at 14 11 03](https://cloud.githubusercontent.com/assets/380007/12550607/9a94ac2a-c36d-11e5-9fa7-79c8db2bbd90.png)

**Comment by pjotrsavitski** [comment]
Please see #75 and #76 for additional points to think about. This means that each activity could possibly have a separate background image?

Please do see the comments about the dimensions. These background images could be big enough (not very big, but still). Loading those could have "slow loading" effects on weak Internet connections.

**Comment by mbrikker** [comment]
We could go with the predefined background picture here as well.

**Comment by pjotrsavitski** [comment]
Ok. Then it will be a predefined one, if time frame allows, then it could also be made configurable or admins.

**Comment by tammets** [comment]
Taustapilt peab jääma sisu osa taha

`dl.dl-horizontal {
background: #fff;
padding: 10px;`

![screen shot 2016-03-21 at 17 40 03](https://cloud.githubusercontent.com/assets/380007/13924209/1daeecac-ef8c-11e5-990e-bfc4f3bb42e1.png)

**Comment by mbrikker** [comment]
Vastav taustapilt, nimega "full2.jpg, asub järgmisel aadressil: https://drive.google.com/folderview?id=0B1cCT4KQ-CA8ZHZUNUhzZmtILU0&usp=sharing
