### ISSUE TITLE
Kasutajaprofiili taustapilt

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#75]
Kasutajal on võimalik üles laadida ja määrata taustapilt (900px x 300px), mida kuvatakse kasutaja profiili lehel ekraanipildil näidatud alas:

![screen shot 2016-01-25 at 14 12 43](https://cloud.githubusercontent.com/assets/380007/12550679/04d90a40-c36e-11e5-93bc-e3564510d4af.png)

**Comment by pjotrsavitski** [comment]
The questions are similar to issue #76. An additional one would be if that makes much sense to do that.

Are other users allowed to access profile pages for others. If not, then it would be a bit strange and not supreme useful functionality.

Maybe some predefined page background image would be the best solution (even if the upload is still needed, some default meaningful background is better than none and possibility to upload something).

In case of non-administrative users and uploads. We will have to be extremely cautious as uploaded images could have completely different size and the dimensions could not be suitable to make the crop (making a meaningful crop at 3 x 1 from a square would be rather problematic and the end result would not be very satisfying).

**Comment by tammets** [comment]
Are other users allowed to access profile pages for others. If not, then it would be a bit strange and not supreme useful functionality. - **Yes, users are allowed to see other users profile pages**
Maybe some predefined page background image would be the best solution (even if the upload is still needed, some default meaningful background is better than none and possibility to upload something). - **Agree but as all graphics are prepared by TU, it can be added later**
In case of non-administrative users and uploads. We will have to be extremely cautious as uploaded images could have completely different size and the dimensions could not be suitable to make the crop (making a meaningful crop at 3 x 1 from a square would be rather problematic and the end result would not be very satisfying). -** There should be clear (text-based) hint about the image dimensions next to uploading form or field.**

**Comment by mbrikker** [comment]
We can go with the predefined page background.

**Comment by tammets** [comment]
Meelis, do you mean that we stick only to predefined background or initially we present predefined background but it can be changed by user afterwards?

**Comment by mbrikker** [comment]
It seems it would be complicated to have users upload their own images, so we could compromise and either a) offer one predefined background per role of the user or b) have a few predefined ones to choose from for each user?

**Comment by pjotrsavitski** [comment]
Both are possible. Role could be determined from the user data and choice from on of the predefined ones would also not be something too problematic.

These would be well made and suitable to the UI (the idea of image stop choose came from ability to select the security image in Swedbank online baking web).

**Comment by mbrikker** [comment]
Let's go with the choice from among a set of predetermined images. Would 8 different images to choose from be okay?

**Comment by pjotrsavitski** [comment]
Should be ok. The logic will be general and flexible. This should also keep the inappropriate content away.

**Comment by mbrikker** [comment]
Kasutajaprofiilide taustapildid: https://drive.google.com/folderview?id=0B1cCT4KQ-CA8YkVMSmVPSElKOFU&usp=sharing
