### ISSUE TITLE
Uuendada ja tõlkida README.md

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#78]
Uuendada ja tõlkida inglise keelde README.md

**Comment by pjotrsavitski** [comment]
This one will probably be left for Sander, as he is the only one who really "knows the ropes".

The operation itself is not supreme complicated. The most problematic ones are some additional plugins and way to configure the system for production use.

**Comment by tammets** [comment]
I agree as it's not critical nor functionality ticket.

**Comment by pjotrsavitski** [comment]
Please note that plugin will not work with PHP version below 5.4 (arrays are defined with **[]** not **array()**, there might be other cases).

The required version should either be set to 5.4+ or the code has to be changed and checked to work with 5.3.
