### ISSUE TITLE
Otsingutulemuste kuvamise arv

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#81]
Otsingutulemuste vorm kuvab hetkel 15 vastet, kuid peab kuvama kõik sobivad.

**Comment by pjotrsavitski** [comment]
Showing all of them could be a bit problematic. If all means a few thousand rows of data. Although, if the results would only show up to a few hundred, then it should not be such a big deal.

**Comment by pjotrsavitski** [comment]
Checked that out. The returned dataset has no hints on total count or if there are any results for the next page.

Maybe this one could give some hints: https://github.com/pods-framework/pods-json-api/issues/32

Although it might be better to crete some "scroll to load more solution". This would try to load the next page (so to say) if that is possible. Or stop with loading more results if last call responded with less than limit or nothing.

**Comment by mbrikker** [comment]
`Although it might be better to crete some "scroll to load more solution". This would try to load the next page (so to say) if that is possible. Or stop with loading more results if last call responded with less than limit or nothing.` - _That would be great._

**Comment by pjotrsavitski** [comment]
The current solution is using a "Load more results" button instead of infinite scroll. Seems to be working well enough. The button disappears once there are no more results to load.

The issue is not closed yet due to some small check-up needs and ordering aspects that have to be dealt with.
