### ISSUE TITLE
Veebiviited "Activity description" väljas

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#82]
Kuvatakse lihttekstina, linki ei ole võimalik "toimivaks muuta".

![unknown](https://cloud.githubusercontent.com/assets/380007/13570956/3e68df6a-e47a-11e5-900b-579ce28d3293.png)

**Comment by pjotrsavitski** [comment]
This one should be easily fixable using something like this: https://docs.angularjs.org/api/ng/directive/ngBindHtml

One thing to be wary about would be that it could potentially allow **any** HTML to be present. If only links are allowed, then there might be some filtering module that would filter out possibly unsafe parts.
