### ISSUE TITLE
Kasutaja saab muuta profiili andmeid front-endist

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#84]
Kasutaja saab muuta registreerimisel sisestatud andmeid oma profiili lehelt.

![screen shot 2016-03-11 at 14 34 46](https://cloud.githubusercontent.com/assets/380007/13702328/6c472d64-e796-11e5-97ab-40e9e35dd974.png)

![screen shot 2016-03-15 at 16 12 58](https://cloud.githubusercontent.com/assets/380007/13780596/d22b0800-eac8-11e5-9955-d912200e7a07.png)

**Comment by pjotrsavitski** [comment]
There is still an issue with Datepicker. Click once - picker shows (although not with selected date), click one more time and nothing is there.

Probable cause could be the value of the data (date picker might expect timestamp or different format).
