### ISSUE TITLE
Vaadata üle kõik muutmis- ja salvestamispäringud

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#88]

**Comment by pjotrsavitski** [comment]
URL query string should not have all the unneeded data in case of POST, PUT.

This could have something to do with use of:

    object.$save(function(data) {
      // Success
    }, function() {
      // Error
    });

This magic seems to leave all the data inside URL QueryString part, although we are dealing with POST here.

Using service directly works well enough:

    ObjectService.save(
      { id: object.id }, {
        data: 'DATA TO BE CHANGED'
      }, function(data) {
        // Succcess
      }, function() {
        // Error
      });

Just look at Group **settings** page, try to save and see what happens. Pay special attention to payload being sent **URL** and **data** part.
