### ISSUE TITLE
Esileht viia vastavusse ekraanipildiga

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#92]
1. Tutvustavad tekstikastid (4tk), tekst must, kasti sisu tekst align: justify
2. Community tekstis üleliigne tühik teacher ja koma vahel
3. Community pealkiri -> Groups

![screen shot 2016-03-21 at 17 48 52](https://cloud.githubusercontent.com/assets/380007/13924547/6e2a6034-ef8d-11e5-811a-abd889286e66.png)

**Comment by mbrikker** [comment]
Vastupidi!
"Community" oli kasti all õige, üleval menüüs oli lihtsalt veel "groups" (ehk siis nüüd oleks vaja **groups>community**, nii üleval kui all). Samuti ei vasta ülemises menüüs ka help alumise kasti pealkirjale (**help>teacher's toolbox**)

**Comment by mbrikker** [comment]
**Uus tekst Teacher's toolbox kastikese alla:**

A collection of pedagogical scenarios for teachers for adapting and improving inquiry activities. Pedagogical instruments and tools for assessing the inquiry proficiency of pupils.
